language: python
python:
- '3.8'
addons:
  ssh_known_hosts: 157.245.101.118
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
install:
- pip install pipenv
- pipenv install
script:
- 'true'
after_success:
- bash ./deploy.sh
notifications:
  email:
    recipients:
    - contact@nxtdoordeals.com
    on_failure: always
